### ISSUE TITLE
fragments in Radon space around -90°

### ISSUE THREAD

**Issue by manuelbauer1603** [antego/Radon#2]
Hi,
concerning radon.cpp:
There seems to be an issue with calculation the Radon space values around -90°.
Fragments can be seen in the linked example sinogram (angles from -180° to +180°):

![sinogram_0](https://user-images.githubusercontent.com/47754011/52967506-980daa00-33aa-11e9-91fb-40a2e9d40903.png)

The reason might be dividing by zero here
https://github.com/antego/radon/blob/5b227d8abe7d8070c9e745d6accad54fb816518d/radon.cpp#L72
or here
https://github.com/antego/radon/blob/5b227d8abe7d8070c9e745d6accad54fb816518d/radon.cpp#L75

Is there an easy fix to this?
Thanks

**Comment by antego** [comment]
https://github.com/antego/radon/commit/71864642f491a066496cd23216ada7e71c40d5e4

**Comment by antego** [comment]
Thanks for reporting the issue!
